# Generated by Django 5.2.5 on 2025-08-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='nota',
            field=models.IntegerField(default=0),
        ),
    ]
