# Generated by Django 5.2.5 on 2025-08-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_alter_alumno_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='materia',
            field=models.CharField(default='lengua', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nota',
            field=models.IntegerField(),
        ),
    ]
