# Generated by Django 5.2.5 on 2025-08-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_alumno_materia_alter_alumno_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes_examenes'),
        ),
    ]
